### ISSUE TITLE
Google Earth Engine Code not viewable

### ISSUE THREAD

**Issue by tobyzawthuhtet** [shijuanchen/forest_degradation_georgia#1]
Dear Publisher,
Your links toward google earth engine code leads to blank google earth engine code page. I would like to have your code read for my knowledge. Thanks.

**Comment by shijuanchen** [comment]
The link leads you to a repository that contains several scripts, instead of one script. If you click the link, a repository named "forest_degradation_georgia" would be added to your "reader" GEE repository. You will be able to see the codes.
