### ISSUE TITLE
I can't find the code "CCDC_run" and "CCDC_land_cover_classification".

### ISSUE THREAD

**Issue by OPQRAIN** [shijuanchen/forest_degradation_georgia#2]
Dear Publisher：
As the title says, I can't find the  code "CCDC_run" and "CCDC_land_cover_classification". If it is convenient, can you tell me where to see them？

**Comment by shijuanchen** [comment]
Dear User,

Thanks for your interest in using the code! I have updated the documentation. The "CCDC_run" and "CCDC_land_cover_classification" were using outdated Collection 1. Now I removed them.

Thanks,
Shijuan
