### ISSUE TITLE
Inquiry Regarding the Forest Mask

### ISSUE THREAD

**Issue by MrShuaiB1** [shijuanchen/forest_degradation_georgia#3]
Dear Dr. Chen,

I would like to express my sincere gratitude for the code you provided, which has been incredibly valuable for conducting research on forest degradation.  However, I have encountered a question regarding the forest mask.

It seems that I could not find any part of the code where the year of the imported forest mask is defined.  Therefore, I am a bit unclear about how to select the appropriate year for the forest mask.  Should I choose the forest mask from the earliest year of the study area, or can I select any year within the research period?  This has left me somewhat confused.

If the year of the imported mask is not specified, how does the CCDC_SMA know which year the mask is associated with?

I would greatly appreciate your clarification on this matter.

Thank you for your time and assistance.

Best regards,
MrShuaiB1

**Comment by shijuanchen** [comment]
Hello,

Yes, you should choose the forest mask from the earliest year of your study. 

Thanks,
Shijuan

**Comment by MrShuaiB1** [comment]
Thank you for your reply! Have a great day!

---- Replied Message ----
| From | Shijuan ***@***.***> |
| Date | 10/31/2024 21:27 |
| To | shijuanchen/forest_degradation_georgia ***@***.***> |
| Cc | MrShuaiB1 ***@***.***>,
Author ***@***.***> |
| Subject | Re: [shijuanchen/forest_degradation_georgia] Inquiry Regarding the Forest Mask (Issue #3) |

Closed #3 as completed.
